# Generated by Django 5.0.1 on 2024-02-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[('office_center', 'Office Center'), ('kitchen', 'Kitchen'), ('studio', 'Studio'), ('meal_service', 'Meal Service'), ('various', 'Various')], max_length=100)),
                ('date_of_entry', models.DateField()),
                ('date_of_exit', models.DateField(blank=True, null=True)),
                ('signed_agreement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='client_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('platform', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person'), ('other', 'Other')], default='-----', max_length=10)),
                ('other_platform_comment', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('clients', models.ManyToManyField(blank=True, related_name='enrolled_courses', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9)),
                ('time_slot', models.CharField(choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], max_length=11)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseschedule_set', to='clients.course')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('laptop1', 'Laptop 1'), ('laptop2', 'Laptop 2'), ('laptop3', 'Laptop 3'), ('laptop4', 'Laptop 4')], max_length=10, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_laptops', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('room_1', 'Room 1'), ('room_2', 'Room 2')], max_length=6)),
                ('seat_number', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.course')),
            ],
            options={
                'unique_together': {('client', 'course'), ('room', 'seat_number')},
            },
        ),
    ]
