# Generated by Django 5.0.1 on 2024-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
