# Generated by Django 5.0.1 on 2024-01-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_course_description_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_slot',
            field=models.CharField(choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], default='Default Time Slot', max_length=20),
        ),
    ]
