# Generated by Django 5.0.1 on 2024-02-13 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_courseschedule_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='seat_number',
            field=models.CharField(choices=[('seat_1', 'Seat 1'), ('seat_2', 'Seat 2'), ('seat_3', 'Seat 3'), ('seat_4', 'Seat 4'), ('seat_5', 'Seat 5'), ('seat_6', 'Seat 6'), ('seat_7', 'Seat 7'), ('seat_8', 'Seat 8')], max_length=10),
        ),
    ]
