# Generated by Django 5.0.1 on 2024-02-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_dayofweek_course_days_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='course',
            name='time_slots',
            field=models.ManyToManyField(to='clients.timeslot'),
        ),
    ]
