# Generated by Django 5.0.1 on 2024-01-31 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_course_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
