# Generated by Django 5.0.1 on 2024-02-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_timeslot_remove_course_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='course',
            name='time_slot',
            field=models.CharField(choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], default='08:30-10:00', max_length=11),
        ),
        migrations.RemoveField(
            model_name='course',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='course',
            name='days_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=9),
        ),
    ]
