# Generated by Django 5.0.1 on 2024-01-31 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_course_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_entry',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_exit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientfile',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='course',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clients.course'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.CharField(choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], max_length=20),
        ),
    ]
