# Generated by Django 5.0.1 on 2024-01-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_course_clients_remove_course_time_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=9),
        ),
        migrations.AddField(
            model_name='course',
            name='time_slot',
            field=models.CharField(choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], default='08:30-10:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ClientFile',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
