# Generated by Django 5.0.1 on 2024-02-08 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_course_days_of_week_alter_course_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='files',
        ),
        migrations.AddField(
            model_name='clientfile',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.client'),
            preserve_default=False,
        ),
    ]
