# Generated by Django 5.0.2 on 2024-02-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='seat_number',
            field=models.CharField(blank=True, choices=[('seat_1', 'Seat 1'), ('seat_2', 'Seat 2'), ('seat_3', 'Seat 3'), ('seat_4', 'Seat 4'), ('seat_5', 'Seat 5'), ('seat_6', 'Seat 6'), ('seat_7', 'Seat 7'), ('seat_8', 'Seat 8'), ('seat_9', 'Seat 9'), ('seat_10', 'Seat 10'), ('seat_11', 'Seat 11'), ('seat_12', 'Seat 12')], max_length=10, null=True),
        ),
    ]
