# Generated by Django 5.0.1 on 2024-02-08 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_files_clientfile_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.client'),
        ),
    ]
