# Generated by Django 5.0.1 on 2024-02-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_schedule_course_course_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='signed_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
