# Generated by Django 5.0.1 on 2024-02-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_course_signed_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='signed_agreement',
        ),
        migrations.AddField(
            model_name='client',
            name='signed_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
