# Generated by Django 5.0.1 on 2024-02-08 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_clientfile_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_slot',
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9)),
                ('time_slot', models.CharField(choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], max_length=11)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clients.course')),
            ],
        ),
    ]
