# Generated by Django 5.0.1 on 2024-02-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_course_signed_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_slot',
            field=models.CharField(choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], default='------', max_length=20),
        ),
    ]
