# Generated by Django 5.0.2 on 2024-02-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_courseschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='days',
            field=models.ManyToManyField(blank=True, to='clients.dayofweek'),
        ),
    ]
