# Generated by Django 5.0.1 on 2024-02-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_course_days_of_week_remove_course_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='costs',
            field=models.FloatField(default=0.0),
        ),
    ]
