# Generated by Django 5.0.1 on 2024-02-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_course_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='client',
        ),
        migrations.AddField(
            model_name='course',
            name='clients',
            field=models.ManyToManyField(related_name='courses', to='clients.client'),
        ),
    ]
