# Generated by Django 5.0.1 on 2024-02-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_course_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='courses', to='clients.client'),
        ),
    ]
