# Generated by Django 5.0.2 on 2024-02-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_courseschedule_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='course_schedules', to='clients.dayofweek'),
        ),
    ]
