# Generated by Django 5.0.2 on 2024-02-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_courseschedule_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='days',
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.dayofweek')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='schedule_entries',
            field=models.ManyToManyField(blank=True, related_name='course_schedules', to='clients.scheduleentry'),
        ),
    ]
