# Generated by Django 5.0.1 on 2024-02-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_course_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='costs',
        ),
        migrations.AlterField(
            model_name='course',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to='clients.client'),
        ),
    ]
