# Generated by Django 5.0.1 on 2024-02-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_course_client_course_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='client_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_files', to='clients.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='files',
            field=models.ManyToManyField(related_name='clients', to='clients.clientfile'),
        ),
    ]
