# Generated by Django 5.0.2 on 2024-02-15 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_remove_courseschedule_days_scheduleentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='schedule_entries',
        ),
        migrations.CreateModel(
            name='CourseScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.courseschedule')),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.scheduleentry')),
            ],
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='course_schedules', through='clients.CourseScheduleEntry', to='clients.scheduleentry'),
        ),
    ]
