# Generated by Django 5.0.1 on 2024-02-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_remove_course_costs_alter_course_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='other_platform_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='platform',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person'), ('other', 'Other')], default='online', max_length=10),
        ),
    ]
