# Generated by Django 5.0.1 on 2024-02-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_clientfile_client_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfile',
            name='client',
        ),
    ]
