# Generated by Django 5.0.2 on 2024-02-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_remove_courseschedule_schedule_entries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='day',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
