# Generated by Django 5.0.2 on 2024-02-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_remove_scheduleentry_day_scheduleentry_friday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='friday_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_schedule_entries', to='clients.timeslot'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='monday_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_schedule_entries', to='clients.timeslot'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='saturday_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_schedule_entries', to='clients.timeslot'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='sunday_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_schedule_entries', to='clients.timeslot'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='thursday_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_schedule_entries', to='clients.timeslot'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='tuesday_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_schedule_entries', to='clients.timeslot'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='wednesday_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_schedule_entries', to='clients.timeslot'),
        ),
    ]
