# Generated by Django 5.0.2 on 2024-02-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_scheduleentry_time_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='saturday_time_slot',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='sunday_time_slot',
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='friday_time_slot',
            field=models.CharField(blank=True, choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='monday_time_slot',
            field=models.CharField(blank=True, choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='thursday_time_slot',
            field=models.CharField(blank=True, choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='tuesday_time_slot',
            field=models.CharField(blank=True, choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='wednesday_time_slot',
            field=models.CharField(blank=True, choices=[('08:30-10:00', '08:30-10:00'), ('10:30-12:00', '10:30-12:00'), ('13:30-15:00', '13:30-15:00')], max_length=11, null=True),
        ),
    ]
