# Generated by Django 5.0.2 on 2024-02-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_remove_scheduleentry_saturday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='clients.course'),
        ),
    ]
