# Generated by Django 5.0.2 on 2024-02-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_alter_scheduleentry_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='assigned_to_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_laptops', to='clients.resource'),
        ),
    ]
