# Generated by Django 5.0.2 on 2024-02-17 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_laptop_assigned_to_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_client_laptops', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='assigned_to_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptops', to='clients.resource'),
        ),
    ]
